# Generated by Django 2.1.7 on 2019-03-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20190304_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CatData',
            new_name='Cat',
        ),
    ]
