# Generated by Django 2.1.7 on 2019-03-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_image_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
